"""Equipment crafting data, extracted verbatim from the game's frontend bundle.

Generated, not hand-written: 154 recipes across three workshops. Editing this
by hand risks silent drift from the server, so re-extract instead.
"""
from __future__ import annotations

# workshop id -> city, profession, category, and the items it can make.
CRAFT_WORKSHOPS = {
    "thunder_forge": {
        "city_id": "city_1",
        "profession": "armorsmith",
        "category": "metal",
        "items": (
            "one_handed_sword_t1",
            "one_handed_sword_t2",
            "one_handed_sword_t3",
            "one_handed_sword_t4",
            "one_handed_sword_t5",
            "one_handed_sword_t6",
            "one_handed_sword_t7",
            "two_handed_sword_t1",
            "two_handed_sword_t2",
            "two_handed_sword_t3",
            "two_handed_sword_t4",
            "two_handed_sword_t5",
            "two_handed_sword_t6",
            "two_handed_sword_t7",
            "two_handed_axe_t1",
            "two_handed_axe_t2",
            "two_handed_axe_t3",
            "two_handed_axe_t4",
            "two_handed_axe_t5",
            "two_handed_axe_t6",
            "two_handed_axe_t7",
            "plate_armor_t1",
            "plate_armor_t2",
            "plate_armor_t3",
            "plate_armor_t4",
            "plate_armor_t5",
            "plate_armor_t6",
            "plate_armor_t7",
            "plate_helmet_t1",
            "plate_helmet_t2",
            "plate_helmet_t3",
            "plate_helmet_t4",
            "plate_helmet_t5",
            "plate_helmet_t6",
            "plate_helmet_t7",
            "plate_boots_t1",
            "plate_boots_t2",
            "plate_boots_t3",
            "plate_boots_t4",
            "plate_boots_t5",
            "plate_boots_t6",
            "plate_boots_t7",
            "plate_greaves_t1",
            "plate_greaves_t2",
            "plate_greaves_t3",
            "plate_greaves_t4",
            "plate_greaves_t5",
            "plate_greaves_t6",
            "plate_greaves_t7",
            "plate_gauntlets_t1",
            "plate_gauntlets_t2",
            "plate_gauntlets_t3",
            "plate_gauntlets_t4",
            "plate_gauntlets_t5",
            "plate_gauntlets_t6",
            "plate_gauntlets_t7",
            "shield_t1",
            "shield_t2",
            "shield_t3",
            "shield_t4",
            "shield_t5",
            "shield_t6",
            "shield_t7",
        ),
    },
    "silent_step": {
        "city_id": "city_13",
        "profession": "leatherworker",
        "category": "leather",
        "items": (
            "leather_armor_t1",
            "leather_armor_t2",
            "leather_armor_t3",
            "leather_armor_t4",
            "leather_armor_t5",
            "leather_armor_t6",
            "leather_armor_t7",
            "leather_helmet_t1",
            "leather_helmet_t2",
            "leather_helmet_t3",
            "leather_helmet_t4",
            "leather_helmet_t5",
            "leather_helmet_t6",
            "leather_helmet_t7",
            "leather_boots_t1",
            "leather_boots_t2",
            "leather_boots_t3",
            "leather_boots_t4",
            "leather_boots_t5",
            "leather_boots_t6",
            "leather_boots_t7",
            "leather_pants_t1",
            "leather_pants_t2",
            "leather_pants_t3",
            "leather_pants_t4",
            "leather_pants_t5",
            "leather_pants_t6",
            "leather_pants_t7",
            "leather_gloves_t1",
            "leather_gloves_t2",
            "leather_gloves_t3",
            "leather_gloves_t4",
            "leather_gloves_t5",
            "leather_gloves_t6",
            "leather_gloves_t7",
            "dagger_t1",
            "dagger_t2",
            "dagger_t3",
            "dagger_t4",
            "dagger_t5",
            "dagger_t6",
            "dagger_t7",
        ),
    },
    "arcane_sanctum": {
        "city_id": "city_18",
        "profession": "tailor",
        "category": "arcane",
        "items": (
            "cloth_robe_t1",
            "cloth_robe_t2",
            "cloth_robe_t3",
            "cloth_robe_t4",
            "cloth_robe_t5",
            "cloth_robe_t6",
            "cloth_robe_t7",
            "magic_diadem_t1",
            "magic_diadem_t2",
            "magic_diadem_t3",
            "magic_diadem_t4",
            "magic_diadem_t5",
            "magic_diadem_t6",
            "magic_diadem_t7",
            "cloth_pants_t1",
            "cloth_pants_t2",
            "cloth_pants_t3",
            "cloth_pants_t4",
            "cloth_pants_t5",
            "cloth_pants_t6",
            "cloth_pants_t7",
            "cloth_boots_t1",
            "cloth_boots_t2",
            "cloth_boots_t3",
            "cloth_boots_t4",
            "cloth_boots_t5",
            "cloth_boots_t6",
            "cloth_boots_t7",
            "cloth_gloves_t1",
            "cloth_gloves_t2",
            "cloth_gloves_t3",
            "cloth_gloves_t4",
            "cloth_gloves_t5",
            "cloth_gloves_t6",
            "cloth_gloves_t7",
            "staff_t1",
            "staff_t2",
            "staff_t3",
            "staff_t4",
            "staff_t5",
            "staff_t6",
            "staff_t7",
            "magic_orb_t1",
            "magic_orb_t2",
            "magic_orb_t3",
            "magic_orb_t4",
            "magic_orb_t5",
            "magic_orb_t6",
            "magic_orb_t7",
        ),
    },
}

# recipe id -> ingredients consumed per unit crafted.
CRAFT_RECIPES = {
    "two_handed_sword_t1": (("copper_ingot", 16),),
    "two_handed_sword_t2": (("iron_ingot", 24), ("two_handed_sword_t1", 1),),
    "two_handed_sword_t3": (("steel_ingot", 36), ("echo_instinct", 4), ("two_handed_sword_t2", 1),),
    "two_handed_sword_t4": (("mithril_ingot", 48), ("echo_ferocity", 8), ("two_handed_sword_t3", 1),),
    "two_handed_sword_t5": (("adamantite_ingot", 72), ("echo_distortion", 12), ("two_handed_sword_t4", 1),),
    "two_handed_sword_t6": (("runite_ingot", 108), ("echo_oblivion", 16), ("two_handed_sword_t5", 1),),
    "two_handed_sword_t7": (("astralius_ingot", 144), ("apex_paradigm", 20), ("two_handed_sword_t6", 1),),
    "two_handed_axe_t1": (("copper_ingot", 8), ("pine_plank", 8),),
    "two_handed_axe_t2": (("iron_ingot", 12), ("oak_timber", 12), ("two_handed_axe_t1", 1),),
    "two_handed_axe_t3": (("steel_ingot", 18), ("maple_timber", 18), ("echo_instinct", 4), ("two_handed_axe_t2", 1),),
    "two_handed_axe_t4": (("mithril_ingot", 24), ("yew_slat", 24), ("echo_ferocity", 8), ("two_handed_axe_t3", 1),),
    "two_handed_axe_t5": (("adamantite_ingot", 36), ("black_timber", 36), ("echo_distortion", 12), ("two_handed_axe_t4", 1),),
    "two_handed_axe_t6": (("runite_ingot", 54), ("elder_plank", 54), ("echo_oblivion", 16), ("two_handed_axe_t5", 1),),
    "two_handed_axe_t7": (("astralius_ingot", 72), ("life_plank", 72), ("apex_paradigm", 20), ("two_handed_axe_t6", 1),),
    "one_handed_sword_t1": (("copper_ingot", 8),),
    "one_handed_sword_t2": (("iron_ingot", 12), ("one_handed_sword_t1", 1),),
    "one_handed_sword_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("one_handed_sword_t2", 1),),
    "one_handed_sword_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("one_handed_sword_t3", 1),),
    "one_handed_sword_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("one_handed_sword_t4", 1),),
    "one_handed_sword_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("one_handed_sword_t5", 1),),
    "one_handed_sword_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("one_handed_sword_t6", 1),),
    "dagger_t1": (("copper_ingot", 8),),
    "dagger_t2": (("iron_ingot", 12), ("dagger_t1", 1),),
    "dagger_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("dagger_t2", 1),),
    "dagger_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("dagger_t3", 1),),
    "dagger_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("dagger_t4", 1),),
    "dagger_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("dagger_t5", 1),),
    "dagger_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("dagger_t6", 1),),
    "staff_t1": (("pine_plank", 8),),
    "staff_t2": (("oak_timber", 12), ("staff_t1", 1),),
    "staff_t3": (("maple_timber", 18), ("echo_instinct", 2), ("staff_t2", 1),),
    "staff_t4": (("yew_slat", 24), ("echo_ferocity", 4), ("staff_t3", 1),),
    "staff_t5": (("black_timber", 36), ("echo_distortion", 6), ("staff_t4", 1),),
    "staff_t6": (("elder_plank", 54), ("echo_oblivion", 8), ("staff_t5", 1),),
    "staff_t7": (("life_plank", 72), ("apex_paradigm", 10), ("staff_t6", 1),),
    "shield_t1": (("copper_ingot", 4), ("pine_plank", 4),),
    "shield_t2": (("iron_ingot", 6), ("oak_timber", 6), ("shield_t1", 1),),
    "shield_t3": (("steel_ingot", 9), ("maple_timber", 9), ("echo_instinct", 2), ("shield_t2", 1),),
    "shield_t4": (("mithril_ingot", 12), ("yew_slat", 12), ("echo_ferocity", 4), ("shield_t3", 1),),
    "shield_t5": (("adamantite_ingot", 18), ("black_timber", 18), ("echo_distortion", 6), ("shield_t4", 1),),
    "shield_t6": (("runite_ingot", 27), ("elder_plank", 27), ("echo_oblivion", 8), ("shield_t5", 1),),
    "shield_t7": (("astralius_ingot", 36), ("life_plank", 36), ("apex_paradigm", 10), ("shield_t6", 1),),
    "magic_orb_t1": (("copper_ingot", 4), ("linen_cloth", 4),),
    "magic_orb_t2": (("iron_ingot", 6), ("cotton_cloth", 6), ("magic_orb_t1", 1),),
    "magic_orb_t3": (("steel_ingot", 9), ("woolen_cloth", 9), ("echo_instinct", 2), ("magic_orb_t2", 1),),
    "magic_orb_t4": (("mithril_ingot", 12), ("silk_brocade", 12), ("echo_ferocity", 4), ("magic_orb_t3", 1),),
    "magic_orb_t5": (("adamantite_ingot", 18), ("mageweave_cloth", 18), ("echo_distortion", 6), ("magic_orb_t4", 1),),
    "magic_orb_t6": (("runite_ingot", 27), ("spirit_silk", 27), ("echo_oblivion", 8), ("magic_orb_t5", 1),),
    "magic_orb_t7": (("astralius_ingot", 36), ("divine_silk", 36), ("apex_paradigm", 10), ("magic_orb_t6", 1),),
    "plate_armor_t1": (("copper_ingot", 8),),
    "plate_armor_t2": (("iron_ingot", 12), ("plate_armor_t1", 1),),
    "plate_armor_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("plate_armor_t2", 1),),
    "plate_armor_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("plate_armor_t3", 1),),
    "plate_armor_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("plate_armor_t4", 1),),
    "plate_armor_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("plate_armor_t5", 1),),
    "plate_armor_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("plate_armor_t6", 1),),
    "plate_helmet_t1": (("copper_ingot", 8),),
    "plate_helmet_t2": (("iron_ingot", 12), ("plate_helmet_t1", 1),),
    "plate_helmet_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("plate_helmet_t2", 1),),
    "plate_helmet_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("plate_helmet_t3", 1),),
    "plate_helmet_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("plate_helmet_t4", 1),),
    "plate_helmet_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("plate_helmet_t5", 1),),
    "plate_helmet_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("plate_helmet_t6", 1),),
    "plate_boots_t1": (("copper_ingot", 8),),
    "plate_boots_t2": (("iron_ingot", 12), ("plate_boots_t1", 1),),
    "plate_boots_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("plate_boots_t2", 1),),
    "plate_boots_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("plate_boots_t3", 1),),
    "plate_boots_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("plate_boots_t4", 1),),
    "plate_boots_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("plate_boots_t5", 1),),
    "plate_boots_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("plate_boots_t6", 1),),
    "plate_greaves_t1": (("copper_ingot", 8),),
    "plate_greaves_t2": (("iron_ingot", 12), ("plate_greaves_t1", 1),),
    "plate_greaves_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("plate_greaves_t2", 1),),
    "plate_greaves_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("plate_greaves_t3", 1),),
    "plate_greaves_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("plate_greaves_t4", 1),),
    "plate_greaves_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("plate_greaves_t5", 1),),
    "plate_greaves_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("plate_greaves_t6", 1),),
    "plate_gauntlets_t1": (("copper_ingot", 8),),
    "plate_gauntlets_t2": (("iron_ingot", 12), ("plate_gauntlets_t1", 1),),
    "plate_gauntlets_t3": (("steel_ingot", 18), ("echo_instinct", 2), ("plate_gauntlets_t2", 1),),
    "plate_gauntlets_t4": (("mithril_ingot", 24), ("echo_ferocity", 4), ("plate_gauntlets_t3", 1),),
    "plate_gauntlets_t5": (("adamantite_ingot", 36), ("echo_distortion", 6), ("plate_gauntlets_t4", 1),),
    "plate_gauntlets_t6": (("runite_ingot", 54), ("echo_oblivion", 8), ("plate_gauntlets_t5", 1),),
    "plate_gauntlets_t7": (("astralius_ingot", 72), ("apex_paradigm", 10), ("plate_gauntlets_t6", 1),),
    "leather_armor_t1": (("rough_leather", 8),),
    "leather_armor_t2": (("fine_leather", 12), ("leather_armor_t1", 1),),
    "leather_armor_t3": (("tanned_leather", 18), ("echo_instinct", 2), ("leather_armor_t2", 1),),
    "leather_armor_t4": (("scale_leather", 24), ("echo_ferocity", 4), ("leather_armor_t3", 1),),
    "leather_armor_t5": (("demon_leather", 36), ("echo_distortion", 6), ("leather_armor_t4", 1),),
    "leather_armor_t6": (("dragon_leather", 54), ("echo_oblivion", 8), ("leather_armor_t5", 1),),
    "leather_armor_t7": (("void_leather", 72), ("apex_paradigm", 10), ("leather_armor_t6", 1),),
    "leather_helmet_t1": (("rough_leather", 8),),
    "leather_helmet_t2": (("fine_leather", 12), ("leather_helmet_t1", 1),),
    "leather_helmet_t3": (("tanned_leather", 18), ("echo_instinct", 2), ("leather_helmet_t2", 1),),
    "leather_helmet_t4": (("scale_leather", 24), ("echo_ferocity", 4), ("leather_helmet_t3", 1),),
    "leather_helmet_t5": (("demon_leather", 36), ("echo_distortion", 6), ("leather_helmet_t4", 1),),
    "leather_helmet_t6": (("dragon_leather", 54), ("echo_oblivion", 8), ("leather_helmet_t5", 1),),
    "leather_helmet_t7": (("void_leather", 72), ("apex_paradigm", 10), ("leather_helmet_t6", 1),),
    "leather_boots_t1": (("rough_leather", 8),),
    "leather_boots_t2": (("fine_leather", 12), ("leather_boots_t1", 1),),
    "leather_boots_t3": (("tanned_leather", 18), ("echo_instinct", 2), ("leather_boots_t2", 1),),
    "leather_boots_t4": (("scale_leather", 24), ("echo_ferocity", 4), ("leather_boots_t3", 1),),
    "leather_boots_t5": (("demon_leather", 36), ("echo_distortion", 6), ("leather_boots_t4", 1),),
    "leather_boots_t6": (("dragon_leather", 54), ("echo_oblivion", 8), ("leather_boots_t5", 1),),
    "leather_boots_t7": (("void_leather", 72), ("apex_paradigm", 10), ("leather_boots_t6", 1),),
    "leather_pants_t1": (("rough_leather", 8),),
    "leather_pants_t2": (("fine_leather", 12), ("leather_pants_t1", 1),),
    "leather_pants_t3": (("tanned_leather", 18), ("echo_instinct", 2), ("leather_pants_t2", 1),),
    "leather_pants_t4": (("scale_leather", 24), ("echo_ferocity", 4), ("leather_pants_t3", 1),),
    "leather_pants_t5": (("demon_leather", 36), ("echo_distortion", 6), ("leather_pants_t4", 1),),
    "leather_pants_t6": (("dragon_leather", 54), ("echo_oblivion", 8), ("leather_pants_t5", 1),),
    "leather_pants_t7": (("void_leather", 72), ("apex_paradigm", 10), ("leather_pants_t6", 1),),
    "leather_gloves_t1": (("rough_leather", 8),),
    "leather_gloves_t2": (("fine_leather", 12), ("leather_gloves_t1", 1),),
    "leather_gloves_t3": (("tanned_leather", 18), ("echo_instinct", 2), ("leather_gloves_t2", 1),),
    "leather_gloves_t4": (("scale_leather", 24), ("echo_ferocity", 4), ("leather_gloves_t3", 1),),
    "leather_gloves_t5": (("demon_leather", 36), ("echo_distortion", 6), ("leather_gloves_t4", 1),),
    "leather_gloves_t6": (("dragon_leather", 54), ("echo_oblivion", 8), ("leather_gloves_t5", 1),),
    "leather_gloves_t7": (("void_leather", 72), ("apex_paradigm", 10), ("leather_gloves_t6", 1),),
    "cloth_robe_t1": (("linen_cloth", 8),),
    "cloth_robe_t2": (("cotton_cloth", 12), ("cloth_robe_t1", 1),),
    "cloth_robe_t3": (("woolen_cloth", 18), ("echo_instinct", 2), ("cloth_robe_t2", 1),),
    "cloth_robe_t4": (("silk_brocade", 24), ("echo_ferocity", 4), ("cloth_robe_t3", 1),),
    "cloth_robe_t5": (("mageweave_cloth", 36), ("echo_distortion", 6), ("cloth_robe_t4", 1),),
    "cloth_robe_t6": (("spirit_silk", 54), ("echo_oblivion", 8), ("cloth_robe_t5", 1),),
    "cloth_robe_t7": (("divine_silk", 72), ("apex_paradigm", 10), ("cloth_robe_t6", 1),),
    "magic_diadem_t1": (("linen_cloth", 8),),
    "magic_diadem_t2": (("cotton_cloth", 12), ("magic_diadem_t1", 1),),
    "magic_diadem_t3": (("woolen_cloth", 18), ("echo_instinct", 2), ("magic_diadem_t2", 1),),
    "magic_diadem_t4": (("silk_brocade", 24), ("echo_ferocity", 4), ("magic_diadem_t3", 1),),
    "magic_diadem_t5": (("mageweave_cloth", 36), ("echo_distortion", 6), ("magic_diadem_t4", 1),),
    "magic_diadem_t6": (("spirit_silk", 54), ("echo_oblivion", 8), ("magic_diadem_t5", 1),),
    "magic_diadem_t7": (("divine_silk", 72), ("apex_paradigm", 10), ("magic_diadem_t6", 1),),
    "cloth_pants_t1": (("linen_cloth", 8),),
    "cloth_pants_t2": (("cotton_cloth", 12), ("cloth_pants_t1", 1),),
    "cloth_pants_t3": (("woolen_cloth", 18), ("echo_instinct", 2), ("cloth_pants_t2", 1),),
    "cloth_pants_t4": (("silk_brocade", 24), ("echo_ferocity", 4), ("cloth_pants_t3", 1),),
    "cloth_pants_t5": (("mageweave_cloth", 36), ("echo_distortion", 6), ("cloth_pants_t4", 1),),
    "cloth_pants_t6": (("spirit_silk", 54), ("echo_oblivion", 8), ("cloth_pants_t5", 1),),
    "cloth_pants_t7": (("divine_silk", 72), ("apex_paradigm", 10), ("cloth_pants_t6", 1),),
    "cloth_boots_t1": (("linen_cloth", 8),),
    "cloth_boots_t2": (("cotton_cloth", 12), ("cloth_boots_t1", 1),),
    "cloth_boots_t3": (("woolen_cloth", 18), ("echo_instinct", 2), ("cloth_boots_t2", 1),),
    "cloth_boots_t4": (("silk_brocade", 24), ("echo_ferocity", 4), ("cloth_boots_t3", 1),),
    "cloth_boots_t5": (("mageweave_cloth", 36), ("echo_distortion", 6), ("cloth_boots_t4", 1),),
    "cloth_boots_t6": (("spirit_silk", 54), ("echo_oblivion", 8), ("cloth_boots_t5", 1),),
    "cloth_boots_t7": (("divine_silk", 72), ("apex_paradigm", 10), ("cloth_boots_t6", 1),),
    "cloth_gloves_t1": (("linen_cloth", 8),),
    "cloth_gloves_t2": (("cotton_cloth", 12), ("cloth_gloves_t1", 1),),
    "cloth_gloves_t3": (("woolen_cloth", 18), ("echo_instinct", 2), ("cloth_gloves_t2", 1),),
    "cloth_gloves_t4": (("silk_brocade", 24), ("echo_ferocity", 4), ("cloth_gloves_t3", 1),),
    "cloth_gloves_t5": (("mageweave_cloth", 36), ("echo_distortion", 6), ("cloth_gloves_t4", 1),),
    "cloth_gloves_t6": (("spirit_silk", 54), ("echo_oblivion", 8), ("cloth_gloves_t5", 1),),
    "cloth_gloves_t7": (("divine_silk", 72), ("apex_paradigm", 10), ("cloth_gloves_t6", 1),),
}

