"""Item catalog facts needed to manage inventory and equipment.

Extracted from the game bundle, not hand-written. 154 equippable items across
eight slots, and the ten container types that can be opened.
"""
from __future__ import annotations

# equippable item id -> the equipment slot it occupies.
ITEM_SLOTS = {
    "cloth_boots_t1": "boots",
    "cloth_boots_t2": "boots",
    "cloth_boots_t3": "boots",
    "cloth_boots_t4": "boots",
    "cloth_boots_t5": "boots",
    "cloth_boots_t6": "boots",
    "cloth_boots_t7": "boots",
    "cloth_gloves_t1": "greaves",
    "cloth_gloves_t2": "greaves",
    "cloth_gloves_t3": "greaves",
    "cloth_gloves_t4": "greaves",
    "cloth_gloves_t5": "greaves",
    "cloth_gloves_t6": "greaves",
    "cloth_gloves_t7": "greaves",
    "cloth_pants_t1": "gauntlets",
    "cloth_pants_t2": "gauntlets",
    "cloth_pants_t3": "gauntlets",
    "cloth_pants_t4": "gauntlets",
    "cloth_pants_t5": "gauntlets",
    "cloth_pants_t6": "gauntlets",
    "cloth_pants_t7": "gauntlets",
    "cloth_robe_t1": "chest",
    "cloth_robe_t2": "chest",
    "cloth_robe_t3": "chest",
    "cloth_robe_t4": "chest",
    "cloth_robe_t5": "chest",
    "cloth_robe_t6": "chest",
    "cloth_robe_t7": "chest",
    "dagger_t1": "left_weapon",
    "dagger_t2": "left_weapon",
    "dagger_t3": "left_weapon",
    "dagger_t4": "left_weapon",
    "dagger_t5": "left_weapon",
    "dagger_t6": "left_weapon",
    "dagger_t7": "left_weapon",
    "leather_armor_t1": "chest",
    "leather_armor_t2": "chest",
    "leather_armor_t3": "chest",
    "leather_armor_t4": "chest",
    "leather_armor_t5": "chest",
    "leather_armor_t6": "chest",
    "leather_armor_t7": "chest",
    "leather_boots_t1": "boots",
    "leather_boots_t2": "boots",
    "leather_boots_t3": "boots",
    "leather_boots_t4": "boots",
    "leather_boots_t5": "boots",
    "leather_boots_t6": "boots",
    "leather_boots_t7": "boots",
    "leather_gloves_t1": "greaves",
    "leather_gloves_t2": "greaves",
    "leather_gloves_t3": "greaves",
    "leather_gloves_t4": "greaves",
    "leather_gloves_t5": "greaves",
    "leather_gloves_t6": "greaves",
    "leather_gloves_t7": "greaves",
    "leather_helmet_t1": "head",
    "leather_helmet_t2": "head",
    "leather_helmet_t3": "head",
    "leather_helmet_t4": "head",
    "leather_helmet_t5": "head",
    "leather_helmet_t6": "head",
    "leather_helmet_t7": "head",
    "leather_pants_t1": "gauntlets",
    "leather_pants_t2": "gauntlets",
    "leather_pants_t3": "gauntlets",
    "leather_pants_t4": "gauntlets",
    "leather_pants_t5": "gauntlets",
    "leather_pants_t6": "gauntlets",
    "leather_pants_t7": "gauntlets",
    "magic_diadem_t1": "head",
    "magic_diadem_t2": "head",
    "magic_diadem_t3": "head",
    "magic_diadem_t4": "head",
    "magic_diadem_t5": "head",
    "magic_diadem_t6": "head",
    "magic_diadem_t7": "head",
    "magic_orb_t1": "left_weapon",
    "magic_orb_t2": "left_weapon",
    "magic_orb_t3": "left_weapon",
    "magic_orb_t4": "left_weapon",
    "magic_orb_t5": "left_weapon",
    "magic_orb_t6": "left_weapon",
    "magic_orb_t7": "left_weapon",
    "one_handed_sword_t1": "right_weapon",
    "one_handed_sword_t2": "right_weapon",
    "one_handed_sword_t3": "right_weapon",
    "one_handed_sword_t4": "right_weapon",
    "one_handed_sword_t5": "right_weapon",
    "one_handed_sword_t6": "right_weapon",
    "one_handed_sword_t7": "right_weapon",
    "plate_armor_t1": "chest",
    "plate_armor_t2": "chest",
    "plate_armor_t3": "chest",
    "plate_armor_t4": "chest",
    "plate_armor_t5": "chest",
    "plate_armor_t6": "chest",
    "plate_armor_t7": "chest",
    "plate_boots_t1": "boots",
    "plate_boots_t2": "boots",
    "plate_boots_t3": "boots",
    "plate_boots_t4": "boots",
    "plate_boots_t5": "boots",
    "plate_boots_t6": "boots",
    "plate_boots_t7": "boots",
    "plate_gauntlets_t1": "greaves",
    "plate_gauntlets_t2": "greaves",
    "plate_gauntlets_t3": "greaves",
    "plate_gauntlets_t4": "greaves",
    "plate_gauntlets_t5": "greaves",
    "plate_gauntlets_t6": "greaves",
    "plate_gauntlets_t7": "greaves",
    "plate_greaves_t1": "gauntlets",
    "plate_greaves_t2": "gauntlets",
    "plate_greaves_t3": "gauntlets",
    "plate_greaves_t4": "gauntlets",
    "plate_greaves_t5": "gauntlets",
    "plate_greaves_t6": "gauntlets",
    "plate_greaves_t7": "gauntlets",
    "plate_helmet_t1": "head",
    "plate_helmet_t2": "head",
    "plate_helmet_t3": "head",
    "plate_helmet_t4": "head",
    "plate_helmet_t5": "head",
    "plate_helmet_t6": "head",
    "plate_helmet_t7": "head",
    "shield_t1": "left_weapon",
    "shield_t2": "left_weapon",
    "shield_t3": "left_weapon",
    "shield_t4": "left_weapon",
    "shield_t5": "left_weapon",
    "shield_t6": "left_weapon",
    "shield_t7": "left_weapon",
    "staff_t1": "right_weapon",
    "staff_t2": "right_weapon",
    "staff_t3": "right_weapon",
    "staff_t4": "right_weapon",
    "staff_t5": "right_weapon",
    "staff_t6": "right_weapon",
    "staff_t7": "right_weapon",
    "two_handed_axe_t1": "two_hand_weapon",
    "two_handed_axe_t2": "two_hand_weapon",
    "two_handed_axe_t3": "two_hand_weapon",
    "two_handed_axe_t4": "two_hand_weapon",
    "two_handed_axe_t5": "two_hand_weapon",
    "two_handed_axe_t6": "two_hand_weapon",
    "two_handed_axe_t7": "two_hand_weapon",
    "two_handed_sword_t1": "two_hand_weapon",
    "two_handed_sword_t2": "two_hand_weapon",
    "two_handed_sword_t3": "two_hand_weapon",
    "two_handed_sword_t4": "two_hand_weapon",
    "two_handed_sword_t5": "two_hand_weapon",
    "two_handed_sword_t6": "two_hand_weapon",
    "two_handed_sword_t7": "two_hand_weapon",
}

# Containers that openChests accepts.
OPENABLE_ITEMS = (
    "large_equip_chest",
    "large_weapon_chest",
    "medium_equip_chest",
    "medium_reag_chest",
    "medium_res_chest",
    "medium_weapon_chest",
    "small_equip_chest",
    "small_reag_chest",
    "small_res_chest",
    "small_weapon_chest",
)

# A two-handed weapon occupies both hands, so it conflicts with either.
SLOT_CONFLICTS = {
    "two_hand_weapon": ("left_weapon", "right_weapon"),
    "left_weapon": ("two_hand_weapon",),
    "right_weapon": ("two_hand_weapon",),
}

